--DROPPING TABLES CUSTOMER DIMENSION
drop table FACT_TRANSACTION;
drop table DIM_CUSTOMER;
drop table DIM_PRODUCT;
drop table DIM_STORE;
drop table DIM_DATE;
--CREATING CUSTOMER DIMENSION
CREATE TABLE DIM_CUSTOMER
( CUSTOMER_ID Varchar2(4) NOT NULL,  
  Customer_Name Varchar2(30) NOT NULL, 
  CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)  
);
--CREATING PRODUCT DIMENSION
CREATE TABLE DIM_PRODUCT 
( PRODUCT_ID Varchar2(6) NOT NULL,  
  PRODUCT_NAME Varchar2(30) NOT NULL, 
  SUPPLIER_ID Varchar2(5) NOT NULL,
  SUPPLIER_NAME Varchar2(30) NOT NULL,
  PRICE Number(5,2) NOT NULL,
  CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID)  
);  
--CREATING STORE DIMENSION
CREATE TABLE DIM_STORE
( STORE_ID Varchar2(4) NOT NULL,  
  STORE_NAME Varchar2(20) NOT NULL, 
  CONSTRAINT STORE_PK PRIMARY KEY (STORE_ID)  
);
--CREATING DATE DIMENSION
CREATE TABLE DIM_DATE
AS
(
 SELECT
  ROWNUM AS DATE_ID ,
  DATE_D AS "T_DATE",
  TRIM(TO_CHAR(DATE_D,'Month','nls_date_language=english')) as "MONTH",
  TO_NUMBER(TO_CHAR(DATE_D,'Q')) as "QUARTER",
  TO_NUMBER(TO_CHAR(DATE_D,'YYYY')) as "YEAR"
 FROM
 (
 SELECT
  to_date('2015-12-31','YYYY-MM-DD')+ROWNUM AS DATE_D
 FROM
  dual
  connect by level <= to_date('2016-12-31','YYYY-MM-DD')-to_date('2015-12-31','YYYY-MM-DD') --Range of calendar
 )
);
ALTER TABLE DIM_DATE
ADD CONSTRAINT DATE_PK PRIMARY KEY (DATE_ID);
--Creating Fact Table
CREATE TABLE FACT_TRANSACTION
( TRANSACTION_ID Number(8,0) NOT NULL PRIMARY KEY,
  QUANTITY Number(3,0) NOT NULL,
  CUSTOMER_KEY Varchar2(4),
  PRODUCT_KEY Varchar2(6),
  STORE_KEY Varchar2(4), 
  DATE_KEY NUMBER(3,0),
  TOTAL_SALES NUMBER(8,2)NOT NULL,
  
--Foreign Keys 
  CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_ID),
  CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
  CONSTRAINT FK_STORE FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_ID),
  CONSTRAINT FK_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_ID)
)