INSERT INTO DIM_STORE
(store_id, store_name)
SELECT DISTINCT store_id, store_name
FROM MASTERDATA
INNER JOIN TRANSACTIONS
ON MASTERDATA.product_id = TRANSACTIONS.product_id
ORDER BY store_id;


INSERT INTO DIM_CUSTOMER
(customer_id, customer_name)
SELECT DISTINCT customer_id, customer_name
FROM MASTERDATA
INNER JOIN TRANSACTIONS
ON MASTERDATA.product_id = TRANSACTIONS.product_id
ORDER BY customer_id;

INSERT INTO DIM_PRODUCT
(product_id, product_name,supplier_id,supplier_name, price)
SELECT DISTINCT MASTERDATA.product_id, product_name, supplier_id, supplier_name, price
FROM MASTERDATA
INNER JOIN TRANSACTIONS
ON MASTERDATA.product_id = TRANSACTIONS.product_id
ORDER BY product_id;

INSERT INTO FACT_TRANSACTION
(TRANSACTION_ID,QUANTITY,CUSTOMER_KEY,PRODUCT_KEY,STORE_KEY, date_key,TOTAL_SALES)
SELECT DISTINCT T.TRANSACTION_ID , T.QUANTITY , T.CUSTOMER_ID, M.PRODUCT_ID, T.STORE_ID, D.DATE_ID, T.QUANTITY * M.PRICE AS TOTAL_SALES
FROM MASTERDATA M
  INNER JOIN TRANSACTIONS T
    ON M.product_id = T.PRODUCT_ID
  INNER JOIN DIM_DATE D
    ON D.T_DATE = T.T_DATE;
