--Query 1
SELECT *
FROM (SELECT FACT_TRANSACTION.PRODUCT_KEY, DIM_PRODUCT.PRODUCT_NAME, SUM(FACT_TRANSACTION.TOTAL_SALES) AS SUM_SALES
      From FACT_TRANSACTION
      INNER JOIN DIM_PRODUCT
        ON FACT_TRANSACTION.PRODUCT_KEY = DIM_PRODUCT.PRODUCT_ID
      GROUP BY FACT_TRANSACTION.PRODUCT_KEY, DIM_PRODUCT.PRODUCT_NAME
      ORDER BY SUM(FACT_TRANSACTION.TOTAL_SALES) DESC)
WHERE ROWNUM = 1;
--Query 2
SELECT * 
FROM (SELECT DIM_PRODUCT.SUPPLIER_NAME , SUM(FACT_TRANSACTION.TOTAL_SALES)AS SUM_SALES
      FROM DIM_PRODUCT
      INNER JOIN FACT_TRANSACTION 
        ON DIM_PRODUCT.PRODUCT_ID = FACT_TRANSACTION.PRODUCT_KEY
      INNER JOIN DIM_DATE
        ON DIM_DATE.DATE_ID = FACT_TRANSACTION.DATE_KEY
      WHERE (DIM_DATE.MONTH = 'August')
      GROUP BY DIM_PRODUCT.SUPPLIER_NAME
      ORDER BY SUM(FACT_TRANSACTION.TOTAL_SALES) DESC)
WHERE ROWNUM <= 3;
--Query 3
SELECT * 
FROM (SELECT DIM_STORE.STORE_NAME, SUM(FACT_TRANSACTION.TOTAL_SALES) AS SUM_SALES 
      FROM DIM_STORE
      INNER JOIN FACT_TRANSACTION 
        ON DIM_STORE.STORE_ID = FACT_TRANSACTION.STORE_KEY
      INNER JOIN DIM_DATE
        ON DIM_DATE.DATE_ID = FACT_TRANSACTION.DATE_KEY
      WHERE (DIM_DATE.MONTH = 'August')
      GROUP BY DIM_STORE.STORE_NAME
      ORDER BY SUM(FACT_TRANSACTION.TOTAL_SALES) DESC) 
WHERE ROWNUM <= 3;
--Query 4
SELECT * 
FROM (SELECT DIM_PRODUCT.PRODUCT_ID, COUNT(FACT_TRANSACTION.TOTAL_SALES) AS TOTAL_TRANSACTIONS , SUM(FACT_TRANSACTION.QUANTITY) AS QUANTITY_OF_PRODUCTS
      FROM DIM_PRODUCT 
      INNER JOIN FACT_TRANSACTION 
        ON DIM_PRODUCT.PRODUCT_ID = FACT_TRANSACTION.PRODUCT_KEY 
      INNER JOIN DIM_DATE
        ON DIM_DATE.DATE_ID = FACT_TRANSACTION.DATE_KEY
      WHERE (DIM_DATE.YEAR = '2016')
      GROUP BY DIM_PRODUCT.PRODUCT_ID
      ORDER BY COUNT(FACT_TRANSACTION.TOTAL_SALES) DESC)
WHERE ROWNUM =1;
--Query 5
SET SERVEROUTPUT ON;
DECLARE
P_NAME DIM_PRODUCT.PRODUCT_NAME% TYPE;
Q1_2016 DIM_DATE.QUARTER% TYPE;
Q2_2016 DIM_DATE.QUARTER% TYPE;
Q3_2016 DIM_DATE.QUARTER% TYPE;
Q4_2016 DIM_DATE.QUARTER% TYPE;
CURSOR curs_QUARTER1 IS
    SELECT DIM_PRODUCT.PRODUCT_NAME, SUM(FACT_TRANSACTION.total_sales) AS Q1_2016
    FROM DIM_PRODUCT  
    INNER JOIN FACT_TRANSACTION
      ON  DIM_PRODUCT.PRODUCT_ID = FACT_TRANSACTION.product_key 
    INNER JOIN DIM_DATE
      ON DIM_DATE.date_id = FACT_TRANSACTION.date_key
    WHERE(DIM_DATE.QUARTER = '1')
    GROUP BY DIM_PRODUCT.PRODUCT_NAME
    ORDER BY DIM_PRODUCT.PRODUCT_NAME ASC;
CURSOR curs_QUARTER2 IS
      SELECT DIM_PRODUCT.PRODUCT_NAME, SUM(FACT_TRANSACTION.total_sales) AS Q1_2016
    FROM DIM_PRODUCT  
    INNER JOIN FACT_TRANSACTION
      ON  DIM_PRODUCT.PRODUCT_ID = FACT_TRANSACTION.product_key 
    INNER JOIN DIM_DATE
      ON DIM_DATE.date_id = FACT_TRANSACTION.date_key
    WHERE(DIM_DATE.QUARTER = '2')
    GROUP BY DIM_PRODUCT.PRODUCT_NAME
    ORDER BY DIM_PRODUCT.PRODUCT_NAME ASC;
CURSOR curs_QUARTER3 IS
      SELECT DIM_PRODUCT.PRODUCT_NAME, SUM(FACT_TRANSACTION.total_sales) AS Q1_2016
    FROM DIM_PRODUCT  
    INNER JOIN FACT_TRANSACTION
      ON  DIM_PRODUCT.PRODUCT_ID = FACT_TRANSACTION.product_key 
    INNER JOIN DIM_DATE
      ON DIM_DATE.date_id = FACT_TRANSACTION.date_key
    WHERE(DIM_DATE.QUARTER = '3')
    GROUP BY DIM_PRODUCT.PRODUCT_NAME
    ORDER BY DIM_PRODUCT.PRODUCT_NAME ASC;
CURSOR curs_QUARTER4 IS
      SELECT DIM_PRODUCT.PRODUCT_NAME, SUM(FACT_TRANSACTION.total_sales) AS Q1_2016
    FROM DIM_PRODUCT  
    INNER JOIN FACT_TRANSACTION
      ON  DIM_PRODUCT.PRODUCT_ID = FACT_TRANSACTION.product_key 
    INNER JOIN DIM_DATE
      ON DIM_DATE.date_id = FACT_TRANSACTION.date_key
    WHERE(DIM_DATE.QUARTER = '4')
    GROUP BY DIM_PRODUCT.PRODUCT_NAME
    ORDER BY DIM_PRODUCT.PRODUCT_NAME ASC;
BEGIN
  OPEN curs_QUARTER1;
  OPEN curs_QUARTER2;
  OPEN curs_QUARTER3;
  OPEN curs_QUARTER4;
  DBMS_OUTPUT.PUT_LINE('' || rpad('P_NAME',15) || '   ' || rpad('Q1_2016',8)|| '   ' || rpad('Q2_2016',8)|| '   ' || rpad('Q3_2016',8)|| '   ' || rpad('Q4_2016',8) );
  Loop
    FETCH curs_QUARTER1 INTO P_NAME,Q1_2016;
    FETCH curs_QUARTER2 INTO P_NAME,Q2_2016;
    FETCH curs_QUARTER3 INTO P_NAME,Q3_2016;
    FETCH curs_QUARTER4 INTO P_NAME,Q4_2016;
    DBMS_OUTPUT.PUT_LINE('' || rpad(P_NAME,15) || '   ' || rpad(Q1_2016,8)|| '   ' || rpad(Q2_2016,8)|| '   ' || rpad(Q3_2016,8)|| '   ' || rpad(Q4_2016,8) );
  exit when curs_QUARTER1%notfound;
  END LOOP;
  CLOSE curs_QUARTER1;
  CLOSE curs_QUARTER2;
  CLOSE curs_QUARTER3;
  CLOSE curs_QUARTER4;
END;
/
--Query 6
SELECT DIM_STORE.STORE_ID, DIM_PRODUCT.PRODUCT_ID, SUM(FACT_TRANSACTION.TOTAL_SALES) AS STORE_TOTAL
FROM DIM_STORE
INNER JOIN FACT_TRANSACTION 
  ON DIM_STORE.STORE_ID = FACT_TRANSACTION.STORE_KEY
INNER JOIN DIM_PRODUCT
  ON DIM_PRODUCT.PRODUCT_ID = FACT_TRANSACTION.PRODUCT_KEY
GROUP BY(DIM_STORE.STORE_ID, DIM_PRODUCT.PRODUCT_ID)
ORDER BY(store_id)ASC;